name: Go

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        working-directory: ./server
        run: go build -v ./...

      - name: Format
        working-directory: ./server
        run: go fmt ./...

      - name: Test
        working-directory: ./server
        run: go test -v ./...

      - name: Run coverage
        working-directory: ./server
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.0

coverage:
  status:
    diff:
    target: 70%
